### ISSUE TITLE
Question: build from .gff3 taking >20 days?

### ISSUE THREAD

**Issue by lokeyCEU** [pcingola/SnpEff#327] opened 2021-06-01 21:15 UTC
Hello,

I am trying to 1) build a SnpEff database for my species, an unpublished bird genome, from our .gff3 file and 2) annotate a population .vcf with the database. I'm not sure if I'm running into an issue yet but I started running the following code 21 days ago:
```
Species=CS_V4
VCF=CS_V4
java -jar snpEff.jar build -gff3 -t -v ${Species} > build.log
java -Xmx8g -jar snpEff.jar -t ${Species} /data/CS_V4/${VCF}.vcf.gz > /data/CS_V4/${VCF}.ann.vcf.gz
```
And after 20 days it has gotten to this point:
```
22600   ...........................00:01:01     Caracterizing exons by splicing (stage 1) :
....................................................................................................
        100000  ....................................................................................................
        200000  ....................................................................................................
        300000  ....................................................................................................
        400000  ....................................................................................................
        500000  ....................................................................................................
        600000  ....................................................................................................
        700000  ..............
1 days 12:37:55 Caracterizing exons by splicing (stage 2) :
```
Here are the details: running snpEff-4.3 on GNU/Linux x86_64
```
PID USER      PR  NI    VIRT    RES    SHR S  %CPU %MEM     TIME+ COMMAND
2310 me     20   0   32.2g   2.1g  19328 S 100.3  0.4  29230:24 java
```
The .gff3 file (small subset attached) is 96Mb.
[CS_V4_EXAMPLE.txt](https://github.com/pcingola/SnpEff/files/6580579/CS_V4_EXAMPLE.txt)

Thanks for any help

**Comment by pcingola** [comment] 2021-06-03 15:26
Some comments:
- As a reference, building a SnpEff database for the human genome takes 10 minutes.
- You are running the "build" command, which is very memory intensive, without an `-Xmx` option, so that might be an issue
- If the issue is not memory, I'm afraid something might be terribly wrong with the GFF file you are providing.

I cannot dig any deeper with the information you are providing.
Here are some tips on how to provide information: http://pcingola.github.io/SnpEff/help/

**Comment by lokeyCEU** [comment] 2021-06-03 15:30
I've checked my .gff3 file against others and it doesn't seem to have any problems.
I provided the .gff3 file (CS_V4_EXAMPLE.txt) for two genes, how large of a sample would you need to test any problems?

**Comment by pcingola** [comment] 2021-06-03 15:50
Did you re-run with propper memory settings?

**Comment by lokeyCEU** [comment] 2021-06-07 18:10
Hmm I reran it with 
`java -Xmx150g -jar snpEff.jar build -gff3 -t -v CS_V4`
it did run faster (finished stage 1 in 8 hours instead of 26) but ran stage 2 for 24 hrs before it was killed.

I'm going to go through the .gff3 again and I'll upload a subset of the file if I still find no issues.

**Comment by pcingola** [comment] 2021-06-09 11:20
GFF files are always riddled with errors and inconsistencies.
If you have a GTF file, it would be much better.

**Comment by pcingola** [comment] 2021-06-14 11:17
I assume that the problem could be related to many genes have thousands of exons (or an error in the GFF file creating that problem?)

Let me know if you'd like to share the full genome file for debugging purposes.
I'm closing the issue since I don't have enough information to replicate the problem or debug it.

**Closed by pcingola** 2021-06-14 11:17 UTC

**Comment by lokeyCEU** [comment] 2021-07-07 21:13
Reopening as I reformated and reran SnpEff. I also attach more information.

I tried running -build on a .gff and a .gff3 (haven't gotten the .gtf formatting down yet). I used the following commands:
`java -Xmx50g -jar snpEff.jar build -t -v CS_V4` & `java -Xmx50g -jar snpEff.jar build -t -gff3 -v CS_V4`
For the .gff and .gff3 respectively. 

Below I attach the .gff & .gff3 files as well as the outputs from each run. Each .gff and their .log files are subsets of the total file, but the results are the same on the whole file.

For the .gff run
line 4264 is when the warnings and build command ends.
line 4287 is where the annotation command starts

For the .gff3 run it never stops characterizing exons by splicing, as before.

Could I get an example .gtf & .gff3 file that does run with SnpEff so I can see where the formatting is screwy? I tried downloading the human database through SnpEff but all the files are .bin's.
[CS_V4.GeMoMa.Ragoo.gff.gz](https://github.com/pcingola/SnpEff/files/6780095/CS_V4.GeMoMa.Ragoo.gff.gz)
[CS_V4.GeMoMa.Ragoo.gff3.gz](https://github.com/pcingola/SnpEff/files/6780096/CS_V4.GeMoMa.Ragoo.gff3.gz)
[SnpEff.2196224.gff.log](https://github.com/pcingola/SnpEff/files/6780097/SnpEff.2196224.gff.log)
[SnpEff.2196230.gff3.log](https://github.com/pcingola/SnpEff/files/6780102/SnpEff.2196230.gff3.log)

**Comment by pcingola** [comment] 2021-07-08 16:47
I've used SnpEff v5.0 and in both cases the process finishes in less than 20 seconds on my laptop. 

There are several errors:

1) You are not providing a genomic sequence (FASTA), sometimes this is included in the GFF, but in you case it's not.

2) You are not providing neither a "protein.fa" (FASTA of protein sequences), not a "cds.fa" (FASTA of CDS sequences). Without these SnpEff has no way to check if the database has been correctly built. You really should to provide either of those files.

3) The GFF and GFF3 seem to represent different genomes. Are they supposed to be the same genome? 

4) Many of the entries in the GFF3 file, don't have the mandatory 'ID' attribute

5) in both GFF and GFF3 files, the exon parents are pointing to genes instead of transcripts.

6) ID must be unique, your GFF file has duplicated ID, e.g.
```
$ grep CSPIXG000280.3 CS_V4.GeMoMa.Ragoo.gff | grep -w gene
2	GeMoMa	gene	357084	373896	.	+	.	ID=CSPIXG000280.3;Name=GeMoMa%20prediction
5	GeMoMa	gene	5236230	5273493	.	+	.	ID=CSPIXG000280.3;Name=GeMoMa%20prediction
23	GeMoMa	gene	772552	810413	.	+	.	ID=CSPIXG000280.3;Name=GeMoMa%20prediction
10	GeMoMa	gene	487069	5540386	.	+	.	ID=CSPIXG000280.3;Name=GeMoMa%20prediction
18	GeMoMa	gene	8964863	8977779	.	+	.	ID=CSPIXG000280.3;Name=GeMoMa%20prediction
```

These are just the errors I could find in 10 minutes, but it hints that your GFF file/s need to be fixed and the proper additional information (FASTA files) have to be provided to build the database.

I hope this helps.

   Pablo

**Comment by lokeyCEU** [comment] 2021-07-08 22:16
This is helpful, trying to get the .gff formatting down is tricky. Could I please get an example .gff & .gtf that work with SnpEff so that I can use them as reference for formatting? This may also be a useful for others in the examples folder.

Thank you for your help!
Mitch

**Comment by chenqing-1996** [comment] 2021-08-22 09:23
> This is helpful, trying to get the .gff formatting down is tricky. Could I please get an example .gff & .gtf that work with SnpEff so that I can use them as reference for formatting? This may also be a useful for others in the examples folder.
> 
> Thank you for your help!
> Mitch

Hello lokeyCEU,
I had the same problem as you in building the database. Have you solved it ? Can you give me some help? Thank you so much.

**Comment by aude-darracq** [comment] 2022-08-11 07:28
I had a same issue and I used a gff3 validator (http://genometools.org/cgi-bin/gff3validator.cgi) to remove or change issues spotted by the validator. I don't know exactly which issue was responsible of the "snpeff never-end" but it worked.

**Comment by lokeyCEU** [comment] 2022-08-11 13:35
> I had the same issue and I used a gff3 validator (http://genometools.org/cgi-bin/gff3validator.cgi) to remove or change issues spotted by the validator. I don't know exactly which issue was responsible of the "snpeff never-end" but it worked.

Hi Aude,

I ended up using VEP instead. Worked first try. As mentioned the gff format should fit what is seen here https://github.com/The-Sequence-Ontology/Specifications/blob/master/gff3.md . 

If you post an example of your file (head) then maybe we can spot problems.

Best,
Mitch

**Comment by aude-darracq** [comment] 2022-08-11 13:46
Hi, 

Thanks for the suggestion, but I fixed the issue. It was just a comment to help other people getting this error. 
For me, the solution was to use a gff validator on my gff3 file, correct it and run SNPeff again. The only thing I don't know is which one of the errors highlighted by the validator was responsible of the SNPEff issue (because I had many errors and I  have corrected them in one go).

Regards,
Aude

**Comment by pcingola** [comment] 2022-08-11 14:05
There is detailed documentation on how GTF/GFF parsing works and how SnpEff tries to overcome errors in the GFF files:

http://pcingola.github.io/SnpEff/se_build_db_gff_gtf/

Just to be clear, SnpEff could decide to silently ignore all these issues and plow ahead. Taking this approach would lead to potentially inconsistent results and invalid conclusions from your data, sometimes even misleading research or, even worse, clinical decisions that affect patients' lives.

That's why I decided to be more strict, showing an error and refusing to save the database if these conditions are not met and the models cannot be checked using protein and cds FASTA files.

**Comment by lokeyCEU** [comment] 2022-08-11 15:10
> Thanks for the suggestion, but I fixed the issue. It was just a comment to help other people getting this error. 
@ Aude: Oh woops I missed the "but it worked" at the end of the sentence! Morning problems blegh haha.
Thanks for dropping the tip, I'll have to try it on my next run!

> showing an error and refusing to save the database
@ Pablo: Mine never received an error, it just ran forever (20 days) without stopping. Do you think it's still a gff formatting issue?

**Comment by pcingola** [comment] 2022-08-11 15:17
@lokeyCEU I'm not sure what was wrong with your setup. If I remember correctly, tried but was unable to replicate your error condition.

As mentioned in my previous comment: "....the process finishes in less than 20 seconds on my laptop."
I've also provided some details that were wrong in the GFF files you provided (there were six issues mentioned).

In any case, I'm sorry to hear it did not work for you. All the best!
