### ISSUE TITLE
unable bulid new database with gff and fasta: getting ..genome' not found while building

### ISSUE THREAD

**Issue by shanmugavadivelps** [pcingola/SnpEff#259] opened 2020-10-21 16:18 UTC
i have created directory (Fusrarium) inside data directory and added .fa and gff files

changed the snpeff.cog with vi snpeff.config command and added 
# Fusarium_ly genome, F_ly v2
Fusarium.genome: Fusarium_ly

i saved with ctr +S but i failed.

i opened another terminal and gave a command to build "java -jar snpEff.jar build -gff3 -v /home/shanmu/snpEff/data/Fusarium". but the result was as below
00:00:00	SnpEff version SnpEff 5.0 (build 2020-10-04 16:02), by Pablo Cingolani
00:00:00	Command: 'build'
00:00:00	Building database for '/home/shanmu/snpEff/data/Fusarium'
00:00:00	Reading configuration file 'snpEff.config'. Genome: '/home/shanmu/snpEff/data/Fusarium'
00:00:00	Reading config file: /home/shanmu/snpEff/snpEff.config
java.lang.RuntimeException: Property: '/home/shanmu/snpEff/data/Fusarium.genome' not found
	at org.snpeff.interval.Genome.<init>(Genome.java:104)
	at org.snpeff.snpEffect.Config.readGenomeConfig(Config.java:681)
	at org.snpeff.snpEffect.Config.readConfig(Config.java:649)
	at org.snpeff.snpEffect.Config.init(Config.java:480)
	at org.snpeff.snpEffect.Config.<init>(Config.java:117)
	at org.snpeff.SnpEff.loadConfig(SnpEff.java:456)
	at org.snpeff.snpEffect.commandLine.SnpEffCmdBuild.run(SnpEffCmdBuild.java:364)
	at org.snpeff.SnpEff.run(SnpEff.java:1194)
	at org.snpeff.SnpEff.main(SnpEff.java:167)
00:00:00	Logging
00:00:02	Done.

pls help me to solve

**Comment by pcingola** [comment] 2020-10-21 16:31
Can you copy the lines from the config files?

**Comment by shanmugavadivelps** [comment] 2020-10-21 17:07
thanks for your reply sir,

after applying CTR plus s, I am unable to copy from config file.

**Comment by shanmugavadivelps** [comment] 2020-10-22 17:05
sir pls help me to solve the issue

**Comment by shanmugavadivelps** [comment] 2020-10-22 18:12
> Can you copy the lines from the config file?
> Also, you provided the path to the genome directory instead of the genome name.

sir/madam, pls suggest me to solve the issue. I am using ubuntu 20.04 and trying to annotate vcf with gff3 file. pls help me to solve. I tried with snpEff 4.3 and getting same error.

**Comment by pcingola** [comment] 2020-10-23 10:41
I tried it locally and it works OK.
Are you adding those lines to the `/home/shanmu/snpEff/snpEff.config`? (sometimes there is more than one config file and you can get confused).

**Comment by shanmugavadivelps** [comment] 2020-10-23 11:12
I am adding those lines as specified above and the snpEff directory has only one snpEff.config file. I tried with version 4.3 and resulted with same output.

Can you clear me onething, should the config file saved after adding those line?. In that case i have saved with ctrl + S and closed the terminal but terminal gave indication that process is still running. 

next time, I tried with out closing the config terminal, instaed I opened another terminal and executed "java -jar snpEff.jar build -gff3 -v Fusarium". Again same result appeared.

what should i do now. I am really stuck

**Comment by pcingola** [comment] 2020-10-27 12:29
Yes, the config file needs to be saved. Obviously editing the file and not saving it properly was the root cause of your problem.
I'm closing this issue.

**Closed by pcingola** 2020-10-27 12:29 UTC
