### ISSUE TITLE
snpEff regression between versions 5.0 and 5.1

### ISSUE THREAD

**Issue by pgrt** [pcingola/SnpEff#455] opened 2023-01-21 09:21 UTC
Hello,

I used the dataset below:

[example.zip](https://github.com/pcingola/SnpEff/files/10471846/example.zip)

and ran
    snpEff build -c reference/snpeff.config -dataDir . -gff3 ref
(with snpEff 5.1d) but got the output in the below file

[output.txt](https://github.com/pcingola/SnpEff/files/10471847/output.txt)

with a lot of warnings and then errors.

This issue shows up with either version 5.1d from Debian-packaged snpEff or with snpEff 5.1 from bioconda.
Using snpEff 5.0 from bioconda allows one to run the command line with no error.

Thanks a lot for your help if you have time to investigate.

Best regards,
Pierre

**Comment by tillea** [comment] 2023-01-27 05:44
Hi,
the issue above was detected in connection of some test with the Debian packaged version of snpEff and some other Debian package.  Debian is about to be frozen for the next stable release.  It would help if you could give some estimation whether you see any chance to fix this issue in the next week.  Otherwise we might consider to ship snpEff 5.0 in the next stable release to reach some consistency between the packages we are shipping.
Kind regards, Andreas.

**Comment by tillea** [comment] 2023-02-02 10:03
I admit if you could give some response.  Even some "we can't fix this in the next couple of days" would be helpful.

**Comment by pgrt** [comment] 2023-02-03 16:02
Hi,

Would you please be able to provide @tillea and me with the source of any version 5.0 (e.g. 5.0e) please? I don't think it was tagged, but maybe you can point us to the commit of this version?

Thanks,
Pierre

**Comment by tillea** [comment] 2023-02-07 10:50
Hi,
I went back in Git history and realised that in file `main/java/org/snpeff/SnpEff.java` the value of the REVISION variable changed from `e` to `f`.  I have no idea whether this should be considered a "release".  Some confirmation would be extremely helpful.
Kind regards, Andreas.

**Comment by tillea** [comment] 2023-08-29 13:41
Hi again,
we need a solution for Debian to support our users with working pipelines.  This issue is breaking at least one test suite so we can not deliver version 5.1d (which was tagged and this issue was created for) neither the latest tagged release 5.1f since the problem persists unfortunately.
The only option we have to support a stable system is to go back in version history until we find a working release.
I'd like to note that this is not only an issue for Debian.  It also seems that other distributions and packaging efforts like Conda do not provide the latest versions of SnpEff.
Any sign that you can reproduce the issue and are working on this would be really welcome.
Kind regards, Andreas.

**Comment by tillea** [comment] 2023-11-28 16:39
Pinging again.  As I said: It is not really a solution but at least a workaround for the issue if you would set a valid tag for the code that was released as version 5.0e.  For sure we would be even more happy if you would at least give some signal that the problem is acknowledged and you consider working on it in your recent codebase to fix this regression.
Kind regards, Andreas.

**Comment by nileshpatra** [comment] 2023-11-28 18:09
/cc: @pcingola ping on this issue (open since ~1year). Please help check this issue

**Comment by pcingola** [comment] 2023-11-29 12:44
OK, let me look into this.

**Comment by pcingola** [comment] 2023-12-05 11:42
Hi,
  I've checked this and it looks OK.
  In recent versions, SnpEff has been stricter on checking databases. This is to avoid issues with poorly annotated GFF files, which unfortunately are too common. SnpEff will refuse to save any database without properly checking it against a CDS FASTA file or a protein FASTA. If neither FASTA files is provided (like in your example) then it will fail with the appropriate error. For instance in your case it was:
  
```
ERROR: CDS check file '/tmp/example/reference/./ref/cds.fa' not found.
ERROR: Protein check file '/tmp/example/reference/./ref/protein.fa' not found.
ERROR: Database check failed.
```

You can read more about this in this section of the documentation: https://pcingola.github.io/SnpEff/snpeff/build_db/#step-3-checking-the-database

I've tried to improve the documentation a bit by adding a FAQ here: 
https://pcingola.github.io/SnpEff/snpeff/faq/#cannot-build-database-error-database-check-failed

You can revert to the old behaviour by using BOTH command lines: `-noCheckCds -noCheckProtein`.

I've tried to improve the documentation on this, I hope it helps.

Once more apologies for taking such a long time to answer, this issue fell thought the cracks a few times.

I'm closing it, but feel free to re-open if the explanation / documentation is not appropriate.

**Closed by pcingola** 2023-12-05 11:42 UTC

**Comment by tillea** [comment] 2023-12-06 16:21
Thanks a lot.  This was extremely helpful.
