### ISSUE TITLE
snpEff Database and Annotation Warnings/Errors

### ISSUE THREAD

**Issue by brandcm** [pcingola/SnpEff#250] opened 2020-09-07 23:26 UTC
I recently built a custom database and have 328 (out of 20265) transcripts with errors. Further, when I use this database to annotate my VCF files I'm receiving a couple hundred warnings per contig. I'm assuming that these warning are from each genomic site that falls within the range of a transcripts with an error. I was wondering 1) is it possible to obtain a list of the transcripts with errors in my custom database so that they can be excluded? and 2) how can I turn on the warnings during annotation to see where in the genome this is happening? (or are warnings/errors on by default when annotating?). Below is the command I've been using to annotate my VCFs. When I grep for errors/warnings in the output VCFs nothing is coming up despite a number of warnings being listed in the summary output file. 

java -Xmx4g -jar snpEff/snpEff.jar -v [database_name] snpEff/data/[database_name]/[vcf_file] > [output_vcf]

Happy to provide additional information. Any insight that anyone could provide would be greatly appreciated. Thanks!

**Comment by meixilin** [comment] 2020-11-19 07:58
Hi, 

For building the custom database, I found the `-debug` option to be really helpful. In the output log you can find where the errors and warnings come from. 

```
java -Xmx4g -jar snpEff/snpEff.jar -dump -bed -debug -canon [database_name] > [output_bedfile] 2> [output_log]
```

I could not find out if the vcf warnings can be parsed somewhere though >_< However, I am also wondering if there could be a tabulated table for these errors. 

Best ~

**Comment by pcingola** [comment] 2021-01-30 13:44
Apologies for the extremely delayed reply.

1. You can obtain more details by using command line option `-v` (verbose) and even more details by using command line option `-d` (debug)
2. Yes, `-d` should show all the details about each error/warning
3. Error messages list and explanations can be found here: https://pcingola.github.io/SnpEff/se_faq/#error-and-warning-messages
4. Using option `-v` when annotating a VCF shows a tabulated list of warnings and the number of times they occurred.

I hope this helps.
Closing the issue, feel free to reopen if the problem is not solved.

**Closed by pcingola** 2021-01-30 13:44 UTC
